// src/client-react/pages/NotFound.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { faExclamationTriangle } from '@fortawesome/free-solid-svg-icons';

import Shell from '../components/Shell';
import { t } from '../utils/i18n';

export default function NotFound() {
	return (
		<Shell title={t('notFound')} icon={faExclamationTriangle}>
			<div className="_box _center _error-box">
				<img src="https://xn--931a.moe/assets/not-found.jpg" alt="error" />
				<p>{t('notFoundDescription')}</p>
				<Link to="/" className="primary">{t('returnHome')}</Link>
			</div>
		</Shell>
	);
}

// src/client/pages/not-found.vue
<template>
<div class="ipledcug">
	<div class="_fullinfo">
		<div>{{ $ts.notFoundDescription }}</div>
	</div>
</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { faExclamationTriangle } from '@fortawesome/free-solid-svg-icons';
import * as os from '@/os';

export default defineComponent({
	data() {
		return {
			INFO: {
				title: this.$ts.notFound,
				icon: faExclamationTriangle
			},
		}
	},
});
</script>
