// src/client-react/pages/Note.tsx
import React, { useEffect, useState } from 'react';
import { useRouteMatch } from 'react-router-dom';
import { faChevronUp, faChevronDown } from '@fortawesome/free-solid-svg-icons';

import Spinner from '../components/Spinner';
import { api } from '../utils/api';
import { t } from '../utils/i18n';
import { ShellHeader } from '../teleporters';
import { Timeline } from '../components/Timeline';
import { PackedNote } from '../../models/repositories/note';
import { AvatarHeader } from '../components/AvatarHeader';
import { PackedUser } from '../../models/repositories/user';
import Note from '../components/Note';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

export default function Home() {
	const [note, setNote] = useState(null as PackedNote | null);
	const [prevNotes, setPrevNotes] = useState(null as PackedNote[] | null);
	const [nextNotes, setNextNotes] = useState(null as PackedNote[] | null);
	const [hasPrev, setHasPrev] = useState(false);
	const [hasNext, setHasNext] = useState(false);

	const m = useRouteMatch<{ noteId: string }>();


	useEffect(() => {
		api('notes/show', { noteId: m.params.noteId }).then((n) => { 
			setNote(n);

			Promise.all([
				api('users/notes', {
					userId: n.userId,
					untilId: n.id,
					limit: 1,
				}),
				api('users/notes', {
					userId: n.userId,
					sinceId: n.id,
					limit: 1,
				}),
			]).then(([prev, next]) => {
				setHasPrev(prev.length !== 0);
				setHasNext(next.length !== 0);
			});
		});
	}, []);

	const user = note?.user as PackedUser | null;

	const fetchNext = () => { 
		setHasNext(false);
		api('users/notes', {
			userId: note.userId,
			sinceId: note.id,
			limit: 15,
		}).then(setNextNotes);
	};

	const fetchPrev = () => {
		setHasPrev(false);
		api('users/notes', {
			userId: note.userId,
			untilId: note.id,
			limit: 15,
		}).then(setPrevNotes);
	};


	return (
		<div className="_vstack">
			<ShellHeader.Source>
				{user ? <AvatarHeader user={user} title={t('noteOf', { user: user.name || user.username })} /> : null}
			</ShellHeader.Source>

			{ nextNotes ? <div style={{ paddingBottom: 'var(--margin)' }}><Timeline notes={nextNotes} /></div> : null}

			{ hasNext ?
				<button className="_button" onClick={fetchNext}>
					<FontAwesomeIcon icon={faChevronUp} />
				</button>
				: null}
			
			{ note ? <div className="_box"><Note note={note} /></div> : <Spinner /> }

			{ hasPrev ?
				<button className="_button" onClick={fetchPrev}>
					<FontAwesomeIcon icon={faChevronDown} />
				</button>
			: null}

			{ prevNotes ? <div style={{ paddingTop: 'var(--margin)' }}><Timeline notes={prevNotes} /></div> : null}
		</div>
	);
}

// src/client/pages/note.vue
<template>
<div class="mk-note-page">
	<portal to="avatar" v-if="note"><mk-avatar class="avatar" :user="note.user" :disable-preview="true"/></portal>
	<portal to="title" v-if="note">
		<mfm 
			:text="$t('noteOf', { user: note.user.name || note.user.username })"
			:plain="true" :nowrap="true" :custom-emojis="note.user.emojis" :is-note="false"
		/>
	</portal>

	<div v-if="note">
		<button class="_panel _button" v-if="hasNext && !showNext" @click="showNext = true" style="margin: 0 auto var(--margin) auto;"><fa :icon="faChevronUp"/></button>
		<x-notes v-if="showNext" ref="next" :pagination="next"/>
		<hr v-if="showNext"/>

		<mk-remote-caution v-if="note.user.host != null" :href="note.url || note.uri" style="margin-bottom: var(--margin)"/>
		<x-note v-model="note" :key="note.id" :detail="true"/>

		<button class="_panel _button" v-if="hasPrev && !showPrev" @click="showPrev = true" style="margin: var(--margin) auto 0 auto;"><fa :icon="faChevronDown"/></button>
		<hr v-if="showPrev"/>
		<x-notes v-if="showPrev" ref="prev" :pagination="prev" style="margin-top: var(--margin);"/>
	</div>

	<div v-if="error">
		<mk-error @retry="fetch()"/>
	</div>
</div>
</template>

<script lang="ts">
import Vue from 'vue';
import { faChevronUp, faChevronDown } from '@fortawesome/free-solid-svg-icons';
import Progress from '../scripts/loading';
import XNote from '../components/note.vue';
import XNotes from '../components/notes.vue';
import MkRemoteCaution from '../components/remote-caution.vue';

export default Vue.extend({
	metaInfo() {
		return {
			title: this.$t('note') as string
		};
	},
	components: {
		XNote,
		XNotes,
		MkRemoteCaution,
	},
	data() {
		return {
			note: null,
			hasPrev: false,
			hasNext: false,
			showPrev: false,
			showNext: false,
			error: null,
			prev: {
				endpoint: 'users/notes',
				limit: 10,
				params: init => ({
					userId: this.note.userId,
					untilId: this.note.id,
				})
			},
			next: {
				reversed: true,
				endpoint: 'users/notes',
				limit: 10,
				params: init => ({
					userId: this.note.userId,
					sinceId: this.note.id,
				})
			},
			faChevronUp, faChevronDown
		};
	},
	watch: {
		$route: 'fetch'
	},
	created() {
		this.fetch();
	},
	methods: {
		fetch() {
			Progress.start();
			this.$root.api('notes/show', {
				noteId: this.$route.params.note
			}).then(note => {
				this.note = note;					
				Promise.all([
					this.$root.api('users/notes', {
						userId: note.userId,
						untilId: note.id,
						limit: 1,
					}),
					this.$root.api('users/notes', {
						userId: note.userId,
						sinceId: note.id,
						limit: 1,
					}),
				]).then(([prev, next]) => {
					this.hasPrev = prev.length !== 0;
					this.hasNext = next.length !== 0;
				});
			}).catch(e => {
				this.error = e;
			}).finally(() => {
				Progress.done();
			});
		}
	}
});
</script>
